[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions = {columns = 100, lines = 30}

decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"

#regular
size = 16

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
]